apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-manager-api
  namespace: task-manager
  labels:
    app: task-manager-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  #tls:
  #  - hosts:
  #    - hz-dev-x86.imp.io
  #    - test-x86.imp.io
  #    secretName: tls-orion-ingress.cattle-system
  rules:
  #  - host: hz-dev-x86.imp.io
     - http:
        paths:
          - path: //task-manager(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: task-manager-api
                port:
                  number: 8080